Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/nbclient/client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
transistors_raw = pd.read_csv("../data/transistor_data.csv")
transistors = transistors_raw.dropna()
countmean2017 = np.mean(transistors[transistors['Date of Introduction']== 2017]['MOS transistor count'])
print('(2.a) In 2017, the average MOS transistor count was {}\n'.format(countmean2017))

Q1_abv = np.percentile(transistorcounts2017, q=25)
Q2_abv = np.percentile(transistorcounts2017, q=50)
Q3_abv = np.percentile(transistorcounts2017, q=75)

print('The first quartile for 2017 transistor count is {}'.format(Q1_abv))
print('The second quartile for 2017 transistor count is {}'.format(Q2_abv))
print('The third quartile for 2017 transistor count is {}'.format(Q3_abv))

transistorcounts2017 = transistors[transistors['Date of Introduction']== 2017]['MOS transistor count']
plt.boxplot(transistorcounts2017, labels=['MOS Transistor Counts 2017']);
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/tmp/ipykernel_2153/3314595234.py[0m in [0;36m<module>[0;34m[0m
[1;32m      4[0m [0mprint[0m[0;34m([0m[0;34m'(2.a) In 2017, the average MOS transistor count was {}\n'[0m[0;34m.[0m[0mformat[0m[0;34m([0m[0mcountmean2017[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0;34m[0m[0m
[0;32m----> 6[0;31m [0mQ1_abv[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0mpercentile[0m[0;34m([0m[0mtransistorcounts2017[0m[0;34m,[0m [0mq[0m[0;34m=[0m[0;36m25[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      7[0m [0mQ2_abv[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0mpercentile[0m[0;34m([0m[0mtransistorcounts2017[0m[0;34m,[0m [0mq[0m[0;34m=[0m[0;36m50[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      8[0m [0mQ3_abv[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0mpercentile[0m[0;34m([0m[0mtransistorcounts2017[0m[0;34m,[0m [0mq[0m[0;34m=[0m[0;36m75[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'transistorcounts2017' is not defined
NameError: name 'transistorcounts2017' is not defined

